In [7]:
import pickle
import numpy as np

In [14]:
ohe_sex = pickle.load(open('/kaggle/input/notebooks/divjotbedi/titanic-without-pipeline/models/oe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('/kaggle/input/notebooks/divjotbedi/titanic-without-pipeline/models/oe_embarked.pkl', 'rb'))
clf = pickle.load(open('/kaggle/input/notebooks/divjotbedi/titanic-without-pipeline/models/clf.pkl', 'rb'))

In [15]:
input=np.array([[1,'male',36.0,0,0,75.2417,'C']],dtype=object).reshape(1,7)

In [16]:
input_sex=ohe_sex.transform(input[:,1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [17]:
input_sex

array([[0., 1.]])

In [18]:
input_embarked=ohe_embarked.transform(input[:,-1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [19]:
input_embarked

array([[1., 0., 0.]])

In [20]:
input_age=input[:,2].reshape(1,1)

In [21]:
input_age

array([[36.0]], dtype=object)

In [25]:
input_transformed=np.concatenate((input[:,[0,3,4,5]],input_sex,input_embarked,input_age),axis=1)

In [27]:
input_transformed

array([[1, 0, 0, 75.2417, 0.0, 1.0, 1.0, 0.0, 0.0, 36.0]], dtype=object)

In [29]:
input_transformed.shape

(1, 10)

In [30]:
clf.predict(input_transformed)

array([1])