In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder ,MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split 

In [2]:
df=pd.read_csv('/kaggle/input/datasets/brendan45774/test-file/tested.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S


In [4]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [5]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,34.5,0,0,7.8292,Q
1,1,3,female,47.0,1,0,7.0000,S
2,0,2,male,62.0,0,0,9.6875,Q
3,0,3,male,27.0,0,0,8.6625,S
4,1,3,female,22.0,1,1,12.2875,S


In [6]:
train_X,test_X,train_y,test_y=train_test_split(
    df.drop('Survived',axis=1),
df['Survived'],
    test_size=0.3,
    random_state=42)

In [7]:
train_X.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
118,1,male,36.0,0,0,75.2417,C
271,3,male,NaN,0,0,7.7500,Q
114,1,female,63.0,1,0,221.7792,S
311,3,male,22.0,0,0,7.2250,C
131,1,male,53.0,0,0,28.5000,C


In [8]:
test_X.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
321,3,male,25.0,0,0,7.2292,C
324,1,female,39.0,0,0,211.3375,S
388,3,male,21.0,0,0,7.7500,Q
56,3,male,35.0,0,0,7.8958,S
153,3,female,36.0,0,2,12.1833,S


In [9]:
train_y.head()

118    0
271    0
114    1
311    0
131    0
Name: Survived, dtype: int64

In [10]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [11]:
si=SimpleImputer()
train_X_age=si.fit_transform(train_X[['Age']])
test_X_age=si.fit_transform(test_X[['Age']])
train_X_fare=si.fit_transform(train_X[['Fare']])
test_X_fare=si.fit_transform(test_X[['Fare']])

In [12]:
pd.DataFrame(train_X_age).isnull().sum()

0    0
dtype: int64

In [13]:
pd.DataFrame(train_X_fare).isnull().sum()

0    0
dtype: int64

In [14]:
oe_sex=OneHotEncoder(sparse_output=False)
train_X_sex=oe_sex.fit_transform(train_X[['Sex']])
test_X_sex=oe_sex.fit_transform(test_X[['Sex']])

In [15]:
oe_embarked=OneHotEncoder(sparse_output=False)
train_X_embarked=oe_embarked.fit_transform(train_X[['Embarked']])
test_X_embarked=oe_embarked.fit_transform(test_X[['Embarked']])

In [16]:
train_X_embarked

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0

In [17]:
test_X_sex

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

In [18]:
train_X_rem=train_X.drop(columns=['Age','Sex','Embarked','Fare'])
test_X_rem=test_X.drop(columns=['Age','Sex','Embarked','Fare'])

In [19]:
import numpy as np
train_X_transform=np.concatenate((train_X_rem,train_X_fare,train_X_embarked,train_X_sex,train_X_age),axis=1)
test_X_transform=np.concatenate((test_X_rem,test_X_fare,test_X_embarked,test_X_sex,test_X_age),axis=1)

In [20]:
train_X_transform

array([[ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 36.        ],
       [ 3.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 31.03424242],
       [ 1.        ,  1.        ,  0.        , ...,  1.        ,
         0.        , 63.        ],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 46.        ],
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 24.        ],
       [ 3.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 31.03424242]])

In [21]:
train_X_transform.shape

(292, 10)

In [22]:
train_X_rem.head()

,Pclass,SibSp,Parch
118,1,0,0
271,3,0,0
114,1,1,0
311,3,0,0
131,1,0,0


In [23]:
df_train_transformed=pd.DataFrame(train_X_transform,columns=['Pclass','SibSp','Parch','Fare','C','Q','S','Female','Male','Age'])

In [24]:
df_train_transformed.head()

,Pclass,SibSp,Parch,Fare,C,Q,S,Female,Male,Age
0,1.0,0.0,0.0,75.2417,1.0,0.0,0.0,0.0,1.0,36.000000
1,3.0,0.0,0.0,7.7500,0.0,1.0,0.0,0.0,1.0,31.034242
2,1.0,1.0,0.0,221.7792,0.0,0.0,1.0,1.0,0.0,63.000000
3,3.0,0.0,0.0,7.2250,1.0,0.0,0.0,0.0,1.0,22.000000
4,1.0,0.0,0.0,28.5000,1.0,0.0,0.0,0.0,1.0,53.000000


In [25]:
clf=DecisionTreeClassifier()

In [26]:
clf.fit(train_X_transform,train_y)

DecisionTreeClassifier()

In [27]:
pred_y=clf.predict(test_X_transform)
pred_y

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy_score(pred_y,test_y)

1.0

In [30]:
import pickle
import os

os.makedirs('models', exist_ok=True)


In [31]:
pickle.dump(oe_sex,open('models/oe_sex.pkl','wb'))
pickle.dump(oe_embarked,open('models/oe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))
